version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: nextjs_postgres
    restart: always
    environment:
      POSTGRES_USER: mohamed
      POSTGRES_PASSWORD: mohamed
      POSTGRES_DB: platform_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - nextjs-network

volumes:
  pgdata:
    driver: local

networks:
  nextjs-network:
    driver: bridge
